# Generated by Django 4.1.3 on 2022-11-26 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='client_name')),
                ('client_type', models.CharField(max_length=2, verbose_name='client_type')),
                ('fiscal_code', models.CharField(max_length=20, unique=True, verbose_name='client_fiscal_code')),
                ('state_registration', models.CharField(max_length=20, unique=True, verbose_name='client_state_registration')),
                ('fantasy_name', models.CharField(max_length=254, verbose_name='client_fantasy_name')),
                ('address', models.CharField(max_length=300, verbose_name='client_address')),
                ('street_number', models.CharField(max_length=20, null=True, verbose_name='client_street_number')),
                ('neighborhood', models.CharField(max_length=300, verbose_name='client_neighborhood')),
                ('born_date', models.DateField(verbose_name='client_born_date')),
                ('image_path', models.FileField(upload_to='', verbose_name='client_image_path')),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='locations.citymodel')),
            ],
        ),
    ]
