# Generated by Django 4.1.3 on 2022-11-26 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_alter_client_street_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='street_number',
            field=models.CharField(blank=True, default=0, max_length=20, null=True, verbose_name='client_street_number'),
        ),
    ]
