# Generated by Django 4.1.3 on 2022-11-25 02:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StateModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='state_name')),
                ('code', models.CharField(max_length=200, verbose_name='state_code')),
            ],
            options={
                'db_table': 'states',
            },
        ),
        migrations.CreateModel(
            name='CityModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='city_name')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locations.statemodel')),
            ],
            options={
                'db_table': 'cities',
            },
        ),
    ]
